######################################################################
# Automatically generated by qmake (3.0) ? 12? 2 13:46:02 2020
######################################################################

QT += widgets
TEMPLATE = app
TARGET = client
INCLUDEPATH += .

# Input
HEADERS += ui_widget.h widget.h
FORMS += widget.ui
SOURCES += main.cpp
