######################################################################
# Automatically generated by qmake (3.0) ? 12? 2 14:00:57 2020
######################################################################

QT += widgets
TEMPLATE = app
TARGET = test
INCLUDEPATH += .

# Input
SOURCES += simple.cpp
